//
//  MovieDetailModels.swift
//  MoviePlanet
//
//  Created by eyup cimen on 25.09.2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum MovieDetail {
    enum Detail
    {
        struct Request {
            var movieId : Int
        }
        struct Response {
            var movie : Movie
        }
        struct ViewModel {
            struct DisplayedMovie {
                var id : Int
                var title : String
                var releaseDate : String
                var overview : String
                var voteAverage : Double
                var backdropPath : String
                var posterPath : String
            }
            var displayedMovie: DisplayedMovie
        }
    }
    
    enum SimilarMovies {
        struct Request {
            var movieId : Int
        }
        struct Response {
            var movies : [Movie]
        }
        struct ViewModel {
            struct DisplayedMovie {
                var id : Int
                var title : String
                var releaseDate : String
                var overview : String
                var voteAverage : Double
                var imdbLink : String
                var backdropPath : String
                var posterPath : String
            }
            var displayedMovie: [DisplayedMovie]
        }
    }
}
