//
//  MovieListWorker.swift
//  MoviePlanet
//
//  Created by eyup cimen on 23.09.2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class MovieListWorker {
    func doSomeWork() {
    }
}
