//
//  MovieListModels.swift
//  MoviePlanet
//
//  Created by eyup cimen on 23.09.2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum ListMovies {
    enum FetchMovies {
        struct Request {
        }
        struct Response {
            var movies : [Movie]
        }
        struct ViewModel {
            struct DisplayedMovie {
                var id : Int
                var title : String
                var releaseDate : String
                var overview : String
                var voteAverage : Double
                var imdbLink : String
                var backdropPath : String
                var posterPath : String
            }
            var displayedMovie: [DisplayedMovie]
        }
    }
    
    enum FetchSlidersMovies {
        struct Request {
        }
        struct Response {
            var movies : [Movie]
        }
        struct ViewModel {
            struct DisplayedMovie {
                var id : Int
                var title : String
                var releaseDate : String
                var overview : String
                var voteAverage : Double
                var imdbLink : String
                var backdropPath : String
                var posterPath : String
            }
            var displayedMovie: [DisplayedMovie]
            var pathArray : [String]
            var titleArray : [String]
        }
    }
    
    enum FetchSearchMovies {
        struct Request {
        }
        struct Response {
            var movies : [Movie]
        }
        struct ViewModel {
            struct DisplayedMovie {
                var id : Int
                var title : String
                var releaseDate : String
                var overview : String
                var voteAverage : Double
                var imdbLink : String
                var backdropPath : String
                var posterPath : String
            }
            var displayedMovie: [DisplayedMovie]
        }
    }
}
